#if 0
#elif defined(__arm64__) && __arm64__
// Generated by Apple Swift version 5.9.2 (swiftlang-5.9.2.2.56 clang-1500.1.0.2.5)
#ifndef UNIFIEDVIDEOEDITORSDK_SWIFT_H
#define UNIFIEDVIDEOEDITORSDK_SWIFT_H
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#if defined(__OBJC__)
#include <Foundation/Foundation.h>
#endif
#if defined(__cplusplus)
#include <cstdint>
#include <cstddef>
#include <cstdbool>
#include <cstring>
#include <stdlib.h>
#include <new>
#include <type_traits>
#else
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>
#include <string.h>
#endif
#if defined(__cplusplus)
#if defined(__arm64e__) && __has_include(<ptrauth.h>)
# include <ptrauth.h>
#else
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wreserved-macro-identifier"
# ifndef __ptrauth_swift_value_witness_function_pointer
#  define __ptrauth_swift_value_witness_function_pointer(x)
# endif
# ifndef __ptrauth_swift_class_method_pointer
#  define __ptrauth_swift_class_method_pointer(x)
# endif
#pragma clang diagnostic pop
#endif
#endif

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...) 
# endif
#endif
#if !defined(SWIFT_RUNTIME_NAME)
# if __has_attribute(objc_runtime_name)
#  define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
# else
#  define SWIFT_RUNTIME_NAME(X) 
# endif
#endif
#if !defined(SWIFT_COMPILE_NAME)
# if __has_attribute(swift_name)
#  define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
# else
#  define SWIFT_COMPILE_NAME(X) 
# endif
#endif
#if !defined(SWIFT_METHOD_FAMILY)
# if __has_attribute(objc_method_family)
#  define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
# else
#  define SWIFT_METHOD_FAMILY(X) 
# endif
#endif
#if !defined(SWIFT_NOESCAPE)
# if __has_attribute(noescape)
#  define SWIFT_NOESCAPE __attribute__((noescape))
# else
#  define SWIFT_NOESCAPE 
# endif
#endif
#if !defined(SWIFT_RELEASES_ARGUMENT)
# if __has_attribute(ns_consumed)
#  define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
# else
#  define SWIFT_RELEASES_ARGUMENT 
# endif
#endif
#if !defined(SWIFT_WARN_UNUSED_RESULT)
# if __has_attribute(warn_unused_result)
#  define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
# else
#  define SWIFT_WARN_UNUSED_RESULT 
# endif
#endif
#if !defined(SWIFT_NORETURN)
# if __has_attribute(noreturn)
#  define SWIFT_NORETURN __attribute__((noreturn))
# else
#  define SWIFT_NORETURN 
# endif
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA 
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA 
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA 
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif
#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif
#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER 
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility) 
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if !defined(SWIFT_DEPRECATED_OBJC)
# if __has_feature(attribute_diagnose_if_objc)
#  define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
# else
#  define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
# endif
#endif
#if defined(__OBJC__)
#if !defined(IBSegueAction)
# define IBSegueAction 
#endif
#endif
#if !defined(SWIFT_EXTERN)
# if defined(__cplusplus)
#  define SWIFT_EXTERN extern "C"
# else
#  define SWIFT_EXTERN extern
# endif
#endif
#if !defined(SWIFT_CALL)
# define SWIFT_CALL __attribute__((swiftcall))
#endif
#if !defined(SWIFT_INDIRECT_RESULT)
# define SWIFT_INDIRECT_RESULT __attribute__((swift_indirect_result))
#endif
#if !defined(SWIFT_CONTEXT)
# define SWIFT_CONTEXT __attribute__((swift_context))
#endif
#if !defined(SWIFT_ERROR_RESULT)
# define SWIFT_ERROR_RESULT __attribute__((swift_error_result))
#endif
#if defined(__cplusplus)
# define SWIFT_NOEXCEPT noexcept
#else
# define SWIFT_NOEXCEPT 
#endif
#if !defined(SWIFT_C_INLINE_THUNK)
# if __has_attribute(always_inline)
# if __has_attribute(nodebug)
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline)) __attribute__((nodebug))
# else
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline))
# endif
# else
#  define SWIFT_C_INLINE_THUNK inline
# endif
#endif
#if defined(_WIN32)
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL __declspec(dllimport)
#endif
#else
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL 
#endif
#endif
#if defined(__OBJC__)
#if __has_feature(objc_modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import AVFAudio;
@import CoreFoundation;
@import CoreMedia;
@import CoreVideo;
@import Foundation;
@import ObjectiveC;
@import UIKit;
#endif

#endif
#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="UnifiedVideoEditorSDK",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

#if defined(__OBJC__)
@class NSString;
@class NSURL;

SWIFT_PROTOCOL("_TtP21UnifiedVideoEditorSDK8AREffect_")
@protocol AREffect
@property (nonatomic, readonly, copy) NSString * _Nonnull title;
@property (nonatomic, readonly, copy) NSURL * _Nonnull previewImage;
@property (nonatomic, readonly, copy) NSURL * _Nonnull downloadLink;
@property (nonatomic, readonly) BOOL isDownloaded;
/// Do not store localURL. It may be different after relaunching the app.
@property (nonatomic, copy) NSURL * _Nullable localURL;
@property (nonatomic, readonly, copy) NSString * _Nullable type;
@end




@class NSCoder;

SWIFT_CLASS("_TtC21UnifiedVideoEditorSDK21ActivityIndicatorView")
@interface ActivityIndicatorView : UIView
@property (nonatomic) CGRect bounds;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC21UnifiedVideoEditorSDK22AlbumItemConfiguration")
@interface AlbumItemConfiguration : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


/// The Albums configuration
SWIFT_CLASS("_TtC21UnifiedVideoEditorSDK19AlbumsConfiguration")
@interface AlbumsConfiguration : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


@class NSBundle;

SWIFT_CLASS("_TtC21UnifiedVideoEditorSDK19AlertViewController")
@interface AlertViewController : UIViewController
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified contextView;
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified backgroundView;
@property (nonatomic, readonly) UIStatusBarStyle preferredStatusBarStyle;
- (void)viewWillAppear:(BOOL)animated;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end






SWIFT_CLASS("_TtC21UnifiedVideoEditorSDK16AppStateObserver")
@interface AppStateObserver : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class NSNotification;

@interface AppStateObserver (SWIFT_EXTENSION(UnifiedVideoEditorSDK))
- (void)handleApplicationWillResignActiveNotification:(NSNotification * _Nonnull)notification;
- (void)handleApplicationDidBecomeActiveNotification:(NSNotification * _Nonnull)notification;
- (void)handleWillEnterForegroundNotification:(NSNotification * _Nonnull)notification;
- (void)handleWillTerminateNotification:(NSNotification * _Nonnull)notification;
- (void)handleDidEnterBackgroundNotification:(NSNotification * _Nonnull)notification;
@end


SWIFT_PROTOCOL("_TtP21UnifiedVideoEditorSDK24AppStateObserverDelegate_")
@protocol AppStateObserverDelegate
- (void)applicationWillResignActive:(AppStateObserver * _Nonnull)appStateObserver;
- (void)applicationDidBecomeActive:(AppStateObserver * _Nonnull)appStateObserver;
@optional
- (void)applicationWillEnterForeground:(AppStateObserver * _Nonnull)appStateObserver;
- (void)applicationWillTerminateNotification:(AppStateObserver * _Nonnull)appStateObserver;
- (void)applicationDidEnterBackgroundNotification:(AppStateObserver * _Nonnull)appStateObserver;
@end

@class UIScrollView;

SWIFT_CLASS("_TtC21UnifiedVideoEditorSDK22AudioPartSelectionView")
@interface AudioPartSelectionView : UIView <UIScrollViewDelegate>
- (nonnull instancetype)initWithFrame:(CGRect)frame SWIFT_UNAVAILABLE;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder SWIFT_UNAVAILABLE;
- (void)layoutSubviews;
- (void)scrollViewDidScroll:(UIScrollView * _Nonnull)scrollView;
- (void)scrollViewDidEndDecelerating:(UIScrollView * _Nonnull)scrollView;
- (void)scrollViewDidEndDragging:(UIScrollView * _Nonnull)scrollView willDecelerate:(BOOL)decelerate;
- (void)scrollViewWillBeginDragging:(UIScrollView * _Nonnull)scrollView;
- (void)scrollViewWillBeginDecelerating:(UIScrollView * _Nonnull)scrollView;
@end


/// Allows you to implement audio service functionality
SWIFT_CLASS("_TtC21UnifiedVideoEditorSDK12AudioService")
@interface AudioService : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class AVAudioPlayer;

@interface AudioService (SWIFT_EXTENSION(UnifiedVideoEditorSDK)) <AVAudioPlayerDelegate>
- (void)audioPlayerDidFinishPlaying:(AVAudioPlayer * _Nonnull)player successfully:(BOOL)flag;
@end


/// AnalyticsManager is used to interact with banuba analytics servers
SWIFT_CLASS_NAMED("BNBAnalyticsManager")
@interface BNBAnalyticsManager : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end



/// The background configuration.
SWIFT_CLASS("_TtC21UnifiedVideoEditorSDK23BackgroundConfiguration")
@interface BackgroundConfiguration : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


@class NSError;
@class UIImage;
@class UIApplication;

/// Use this class to access Banuba effects from the cloud.
SWIFT_CLASS("_TtC21UnifiedVideoEditorSDK13BanubaARCloud")
@interface BanubaARCloud : NSObject
/// Storing path to the folder witch storing downloaded effects.
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSURL * _Nonnull effectsFolderURL;)
+ (NSURL * _Nonnull)effectsFolderURL SWIFT_WARN_UNUSED_RESULT;
/// Initialize AR cloud client with UUID string.
/// \param arCloudUrl the url that is used to provide effects.
///
/// \param embeddedEffectURLs the list of url to folders which store embedded effects, effects from these folders will be displayed as downloaded.
///
- (nonnull instancetype)initWithArCloudUrl:(NSString * _Nonnull)arCloudUrl embeddedEffectURLs:(NSArray<NSURL *> * _Nullable)embeddedEffectURLs OBJC_DESIGNATED_INITIALIZER;
/// Retrieve ar effects from cloud.
/// Also returns embedded effects which described in embeddedEffectURLs param in init method.
- (void)getAREffectsWithCompletion:(void (^ _Nonnull)(NSArray<id <AREffect>> * _Nullable, NSError * _Nullable))completion;
/// Retrieve the ar effect preview image
- (void)getArEffectPreview:(id <AREffect> _Nonnull)effect completion:(void (^ _Nonnull)(UIImage * _Nullable, NSError * _Nullable))completion;
/// Download the ar effect to local storage.
- (NSUInteger)downloadArEffect:(id <AREffect> _Nonnull)effect downloadProgress:(void (^ _Nullable)(double))downloadProgress completion:(void (^ _Nonnull)(NSURL * _Nullable, NSError * _Nullable))completion;
/// Cancel downloading effect with specific request id.
- (void)cancelDownloadingEffectWithRequestId:(NSUInteger)requestId;
/// This method needs to be called in the UIApplicationDelegate func application(_ application:, handleEventsForBackgroundURLSession identifier:, completionHandler: @escaping () -> Void).
+ (void)application:(UIApplication * _Nonnull)application handleEventsForBackgroundURLSession:(NSString * _Nonnull)identifier completionHandler:(void (^ _Nonnull)(void))completionHandler;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


/// Class supports asynchronous execution block of code
SWIFT_CLASS("_TtC21UnifiedVideoEditorSDK20BanubaAsyncOperation")
@interface BanubaAsyncOperation : NSOperation
@property (nonatomic, readonly, getter=isReady) BOOL ready;
@property (nonatomic, readonly, getter=isExecuting) BOOL executing;
@property (nonatomic, readonly, getter=isFinished) BOOL finished;
@property (nonatomic, readonly, getter=isAsynchronous) BOOL asynchronous;
+ (NSSet<NSString *> * _Nonnull)keyPathsForValuesAffectingValueForKey:(NSString * _Nonnull)key SWIFT_WARN_UNUSED_RESULT;
- (void)start;
/// Subclasses must implement this to perform their work and they must not call <code>super</code>. The default implementation of this function throws an exception.
- (void)main;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC21UnifiedVideoEditorSDK32BaseTrackSelectionViewController")
@interface BaseTrackSelectionViewController : UINavigationController
- (nonnull instancetype)initWithNavigationBarClass:(Class _Nullable)navigationBarClass toolbarClass:(Class _Nullable)toolbarClass OBJC_DESIGNATED_INITIALIZER SWIFT_AVAILABILITY(ios,introduced=5.0);
- (nonnull instancetype)initWithRootViewController:(UIViewController * _Nonnull)rootViewController OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end




SWIFT_CLASS("_TtC21UnifiedVideoEditorSDK14CameraLutStage")
@interface CameraLutStage : NSObject
@property (nonatomic, copy) NSString * _Nonnull name;
@property (nonatomic) BOOL isActive;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_PROTOCOL("_TtP21UnifiedVideoEditorSDK12RenderEffect_")
@protocol RenderEffect
@property (nonatomic, readonly, copy) NSString * _Nonnull name;
@property (nonatomic, readonly) BOOL isLoaded;
@property (nonatomic) BOOL isActive;
- (void)load;
- (void)unload;
- (void)applyWithPixelBuffer:(CVPixelBufferRef _Nonnull)pixelBuffer;
@end


@interface CameraLutStage (SWIFT_EXTENSION(UnifiedVideoEditorSDK)) <RenderEffect>
@property (nonatomic, readonly) BOOL isLoaded;
- (void)load;
- (void)unload;
- (void)applyWithPixelBuffer:(CVPixelBufferRef _Nonnull)pixelBuffer;
@end

@class CALayer;

/// Simple circular progress view
SWIFT_CLASS("_TtC21UnifiedVideoEditorSDK20CircularProgressView")
@interface CircularProgressView : UIView
- (void)layoutSublayersOfLayer:(CALayer * _Nonnull)layer;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


/// The Composition Timeline configuration
SWIFT_CLASS("_TtC21UnifiedVideoEditorSDK32CompositionTimelineConfiguration")
@interface CompositionTimelineConfiguration : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end



/// Setups drafts feature
typedef SWIFT_ENUM(NSInteger, DraftsFeatureConfig, open) {
/// Drafts enabled. Alert asking for saving video to drafts will be presented after editing a video. Drafts button on the start screen  is displayed.
  DraftsFeatureConfigEnabled = 0,
/// Drafts enabled. No alert will be presented after editing a video. Drafts button on the start screen is displayed.
  DraftsFeatureConfigEnabledSaveToDraftsByDefault = 1,
/// Drafts disabled completely. Drafts button on the start screen is hidden.
  DraftsFeatureConfigDisabled = 2,
/// Drafts enabled. Cover screen will not be presented after editing a video.
  DraftsFeatureConfigEnabledAskIfSaveNotExport = 3,
};


/// Holder contains set of speed and visual effexts
SWIFT_CLASS("_TtC21UnifiedVideoEditorSDK25EditorEffectsConfigHolder")
@interface EditorEffectsConfigHolder : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC21UnifiedVideoEditorSDK11EffectModel")
@interface EffectModel : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end




@class UIButton;

SWIFT_CLASS("_TtC21UnifiedVideoEditorSDK22FullscreenActivityView")
@interface FullscreenActivityView : UIView
@property (nonatomic, weak) IBOutlet UIButton * _Nullable additionalButton;
- (void)awakeFromNib;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


/// The Gallery configuration
SWIFT_CLASS("_TtC21UnifiedVideoEditorSDK20GalleryConfiguration")
@interface GalleryConfiguration : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end



SWIFT_CLASS("_TtCC21UnifiedVideoEditorSDK35SmallActivityIndicatorConfiguration12GradientType")
@interface GradientType : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class GradientColorConfiguration;
@protocol ImageConfigurationProtocol;

@interface GradientType (SWIFT_EXTENSION(UnifiedVideoEditorSDK))
+ (GradientType * _Nonnull)color:(GradientColorConfiguration * _Nonnull)color SWIFT_WARN_UNUSED_RESULT;
+ (GradientType * _Nonnull)image:(id <ImageConfigurationProtocol> _Nonnull)image SWIFT_WARN_UNUSED_RESULT;
@end

@class UIColor;

/// The image configuration
SWIFT_PROTOCOL("_TtP21UnifiedVideoEditorSDK26ImageConfigurationProtocol_")
@protocol ImageConfigurationProtocol
@property (nonatomic, readonly, strong) UIImage * _Nullable image;
@property (nonatomic, readonly, strong) UIColor * _Nullable tintColor;
@end


/// The image configuration
SWIFT_CLASS("_TtC21UnifiedVideoEditorSDK18ImageConfiguration")
@interface ImageConfiguration : NSObject <ImageConfigurationProtocol>
/// Image tint color
/// Default is nil.
@property (nonatomic, strong) UIColor * _Nullable tintColor;
/// The image stored or instance by name
@property (nonatomic, readonly, strong) UIImage * _Nullable image;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end



SWIFT_CLASS("_TtC21UnifiedVideoEditorSDK19KeyboardLayoutGuide")
@interface KeyboardLayoutGuide : UILayoutGuide
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER SWIFT_UNAVAILABLE;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class TimeBomb;

SWIFT_CLASS("_TtC21UnifiedVideoEditorSDK7License")
@interface License : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull token;
@property (nonatomic, readonly, copy) NSString * _Nonnull clientId;
@property (nonatomic, readonly) int32_t maxFaces;
/// Video Editor Analytics
@property (nonatomic, readonly) BOOL collectAnalytics;
/// FAR Analytics
@property (nonatomic, readonly) BOOL supportsAnalytics;
@property (nonatomic, readonly) BOOL videoEditorSupportsFaceAR;
@property (nonatomic, readonly) BOOL hasFaceARFeatures;
@property (nonatomic, readonly, copy) NSArray<NSNumber *> * _Nonnull postProcessingEffects;
@property (nonatomic, readonly, copy) NSString * _Nullable arCloudURL;
@property (nonatomic, readonly, strong) TimeBomb * _Nullable timeBomb;
@property (nonatomic, readonly) BOOL supportsFHD;
@property (nonatomic, readonly) BOOL isExportAPIEnabled;
@property (nonatomic, readonly) BOOL isPlaybackAPIEnabled;
@property (nonatomic, readonly) BOOL isVESDKEnabled;
@property (nonatomic, readonly) BOOL isPhotoEditorSDKEnabled;
- (BOOL)isEqual:(id _Nullable)object SWIFT_WARN_UNUSED_RESULT;
+ (License * _Nullable)getLicenseFromToken:(NSString * _Nonnull)token SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end






SWIFT_CLASS("_TtC21UnifiedVideoEditorSDK7NibView")
@interface NibView : UIView
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


/// UIImageView playable preview.
SWIFT_CLASS("_TtC21UnifiedVideoEditorSDK15PlayablePreview")
@interface PlayablePreview : UIImageView
/// Layer class
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) Class _Nonnull layerClass;)
+ (Class _Nonnull)layerClass SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)initWithImage:(UIImage * _Nullable)image OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithImage:(UIImage * _Nullable)image highlightedImage:(UIImage * _Nullable)highlightedImage OBJC_DESIGNATED_INITIALIZER SWIFT_AVAILABILITY(ios,introduced=3.0);
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC21UnifiedVideoEditorSDK26PopoverAlertViewController")
@interface PopoverAlertViewController : UIViewController
- (void)viewDidLoad;
- (void)viewWillAppear:(BOOL)animated;
- (void)viewWillLayoutSubviews;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end

@class UIGestureRecognizer;
@class UITouch;

@interface PopoverAlertViewController (SWIFT_EXTENSION(UnifiedVideoEditorSDK)) <UIGestureRecognizerDelegate>
- (BOOL)gestureRecognizer:(UIGestureRecognizer * _Nonnull)gestureRecognizer shouldReceiveTouch:(UITouch * _Nonnull)touch SWIFT_WARN_UNUSED_RESULT;
@end




SWIFT_CLASS("_TtC21UnifiedVideoEditorSDK22ProgressViewController")
@interface ProgressViewController : UIViewController
- (void)viewDidLoad;
- (void)viewDidDisappear:(BOOL)animated;
- (void)viewDidLayoutSubviews;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end







SWIFT_CLASS("_TtC21UnifiedVideoEditorSDK9SDKLogger")
@interface SDKLogger : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class UIPresentationController;
@protocol UIViewControllerAnimatedTransitioning;
@protocol UIViewControllerInteractiveTransitioning;

SWIFT_CLASS("_TtC21UnifiedVideoEditorSDK26SlideInPresentationManager")
@interface SlideInPresentationManager : NSObject <UIViewControllerTransitioningDelegate>
- (nonnull instancetype)init;
- (UIPresentationController * _Nullable)presentationControllerForPresentedViewController:(UIViewController * _Nonnull)presented presentingViewController:(UIViewController * _Nullable)presenting sourceViewController:(UIViewController * _Nonnull)source SWIFT_WARN_UNUSED_RESULT;
- (id <UIViewControllerAnimatedTransitioning> _Nullable)animationControllerForPresentedController:(UIViewController * _Nonnull)presented presentingController:(UIViewController * _Nonnull)presenting sourceController:(UIViewController * _Nonnull)source SWIFT_WARN_UNUSED_RESULT;
- (id <UIViewControllerAnimatedTransitioning> _Nullable)animationControllerForDismissedController:(UIViewController * _Nonnull)dismissed SWIFT_WARN_UNUSED_RESULT;
- (id <UIViewControllerInteractiveTransitioning> _Nullable)interactionControllerForPresentation:(id <UIViewControllerAnimatedTransitioning> _Nonnull)animator SWIFT_WARN_UNUSED_RESULT;
- (id <UIViewControllerInteractiveTransitioning> _Nullable)interactionControllerForDismissal:(id <UIViewControllerAnimatedTransitioning> _Nonnull)animator SWIFT_WARN_UNUSED_RESULT;
@end


/// The activity indicator configuration.
SWIFT_CLASS("_TtC21UnifiedVideoEditorSDK35SmallActivityIndicatorConfiguration")
@interface SmallActivityIndicatorConfiguration : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

/// The gradient type.
typedef SWIFT_ENUM(NSInteger, GradientTypeAdapter, open) {
  GradientTypeAdapterColor = 0,
  GradientTypeAdapterImage = 1,
};



/// The gradient configuration.
SWIFT_CLASS("_TtCC21UnifiedVideoEditorSDK35SmallActivityIndicatorConfiguration26GradientColorConfiguration")
@interface GradientColorConfiguration : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end



/// The button configuration with text styling and text.
SWIFT_CLASS("_TtC21UnifiedVideoEditorSDK23TextButtonConfiguration")
@interface TextButtonConfiguration : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


/// The text configuration
SWIFT_CLASS("_TtC21UnifiedVideoEditorSDK17TextConfiguration")
@interface TextConfiguration : NSObject
- (id _Nonnull)copy SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC21UnifiedVideoEditorSDK8TimeBomb")
@interface TimeBomb : NSObject
@property (nonatomic, readonly) NSInteger yearBegin;
@property (nonatomic, readonly) NSInteger monBegin;
@property (nonatomic, readonly) NSInteger dayBegin;
@property (nonatomic, readonly) NSInteger yearEnd;
@property (nonatomic, readonly) NSInteger monEnd;
@property (nonatomic, readonly) NSInteger dayEnd;
@property (nonatomic, readonly) BOOL isExpired;
@end

@protocol TimeLineDataSourceDelegate;

SWIFT_PROTOCOL("_TtP21UnifiedVideoEditorSDK18TimeLineDataSource_")
@protocol TimeLineDataSource
/// TimeLineDataSource delegate object
@property (nonatomic, strong) id <TimeLineDataSourceDelegate> _Nullable delegate;
/// timeline preview
@property (nonatomic, strong) UIImage * _Nullable preview;
/// Asset duration
@property (nonatomic, readonly) CMTime duration;
/// Loaded thumbnails
@property (nonatomic, readonly, copy) NSArray<UIImage *> * _Nonnull thumbnails;
/// Is fetching thumbnails finished
@property (nonatomic, readonly) BOOL isAllThumbnailsFetched;
/// Thumbnails count to fetch
@property (nonatomic, readonly) NSInteger thumbnailsCount;
/// Thumbnails height
@property (nonatomic, readonly) CGFloat thumbnailHeight;
/// Load signle thumbnail for specific second
- (void)loadPreviewWithCompletion:(void (^ _Nonnull)(UIImage * _Nullable))completion at:(double)second;
/// Returns thumbnail at index
- (UIImage * _Nullable)getImageAt:(NSInteger)index SWIFT_WARN_UNUSED_RESULT;
/// Load thumbnails with completion
- (void)loadTimelineThumbsWithCompletion:(void (^ _Nullable)(void))completion;
@end


/// TimeLineDataSourceDelegate notify delegate objects about fetching thumbs actions
SWIFT_PROTOCOL("_TtP21UnifiedVideoEditorSDK26TimeLineDataSourceDelegate_")
@protocol TimeLineDataSourceDelegate
@optional
/// timelineDataSource did preload preivew
- (void)timelineDataSource:(id <TimeLineDataSource> _Nonnull)timelineDataSource didPreloadPreview:(UIImage * _Nonnull)preview;
@required
/// timelineDataSource did load thumb image at index
- (void)timelineDataSource:(id <TimeLineDataSource> _Nonnull)timelineDataSource didLoadImage:(UIImage * _Nonnull)image at:(NSInteger)index;
/// timelineDataSource did finish fetching all thumbs
- (void)timelineDataSourceDidFinishThumbnailFetch:(id <TimeLineDataSource> _Nonnull)timelineDataSource;
@end


/// The Time line configuration
SWIFT_CLASS("_TtC21UnifiedVideoEditorSDK25TrimTimeLineConfiguration")
@interface TrimTimeLineConfiguration : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end












@class NSData;

@interface UIImage (SWIFT_EXTENSION(UnifiedVideoEditorSDK))
/// This method doesn’t use copying data, since it can heavily affect performance and memory usage
/// (for high quality photos like 3024x4032 each copy of data has size ~30 Mb, and on slower devices making copy can take up to 0.2 sec).
/// Common idea - we have NSData object which contains raw data, used for UIImage creation. Since we don’t copy underlying data, we need to take control on
/// lifetime of NSData object, otherwise internal content of UIImage will be destroyed.
/// So, we manually transform NSData object into unmanaged pointer and increase its retain count by passRetained call, and in special callback of CGDataProvider,
/// which will be called when UIImage is no longer needed, we release that unmanaged pointer by takeRetainedValue call, to prevent memory leaks.
- (nullable instancetype)initWithBgraDataNoCopy:(NSData * _Nonnull)bgraDataNoCopy width:(NSInteger)width height:(NSInteger)height;
- (CVPixelBufferRef _Nullable)makeBgraPixelBuffer SWIFT_WARN_UNUSED_RESULT;
@end



















SWIFT_CLASS("_TtC21UnifiedVideoEditorSDK28VideoEditorActivityIndicator")
@interface VideoEditorActivityIndicator : UIView
@property (nonatomic) CGRect bounds;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


/// The video editor launch configuration
SWIFT_CLASS("_TtC21UnifiedVideoEditorSDK23VideoEditorLaunchConfig")
@interface VideoEditorLaunchConfig : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC21UnifiedVideoEditorSDK30VideoImageEffectDrawersFactory")
@interface VideoImageEffectDrawersFactory : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


/// Image composition for slideshow creation
SWIFT_CLASS("_TtC21UnifiedVideoEditorSDK22VideoImagesComposition")
@interface VideoImagesComposition : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC21UnifiedVideoEditorSDK13VideoSequence")
@interface VideoSequence : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end





@interface VideoSequence (SWIFT_EXTENSION(UnifiedVideoEditorSDK))
- (BOOL)isEqual:(id _Nullable)object SWIFT_WARN_UNUSED_RESULT;
@end









/// VideoTimeLineCollectionViewHandler displays timeLineDataSource in collectionView
SWIFT_CLASS("_TtC21UnifiedVideoEditorSDK34VideoTimeLineCollectionViewHandler")
@interface VideoTimeLineCollectionViewHandler : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end



@interface VideoTimeLineCollectionViewHandler (SWIFT_EXTENSION(UnifiedVideoEditorSDK)) <TimeLineDataSourceDelegate>
- (void)timelineDataSource:(id <TimeLineDataSource> _Nonnull)timelineDataSource didPreloadPreview:(UIImage * _Nonnull)preview;
- (void)timelineDataSource:(id <TimeLineDataSource> _Nonnull)timelineDataSource didLoadImage:(UIImage * _Nonnull)image at:(NSInteger)index;
- (void)timelineDataSourceDidFinishThumbnailFetch:(id <TimeLineDataSource> _Nonnull)timelineDataSource;
@end

@class UICollectionView;
@class UICollectionViewLayout;
@class NSIndexPath;

@interface VideoTimeLineCollectionViewHandler (SWIFT_EXTENSION(UnifiedVideoEditorSDK)) <UICollectionViewDelegateFlowLayout>
- (CGSize)collectionView:(UICollectionView * _Nonnull)collectionView layout:(UICollectionViewLayout * _Nonnull)collectionViewLayout sizeForItemAtIndexPath:(NSIndexPath * _Nonnull)indexPath SWIFT_WARN_UNUSED_RESULT;
- (CGFloat)collectionView:(UICollectionView * _Nonnull)collectionView layout:(UICollectionViewLayout * _Nonnull)collectionViewLayout minimumInteritemSpacingForSectionAtIndex:(NSInteger)section SWIFT_WARN_UNUSED_RESULT;
- (CGFloat)collectionView:(UICollectionView * _Nonnull)collectionView layout:(UICollectionViewLayout * _Nonnull)collectionViewLayout minimumLineSpacingForSectionAtIndex:(NSInteger)section SWIFT_WARN_UNUSED_RESULT;
@end

@class UICollectionViewCell;

@interface VideoTimeLineCollectionViewHandler (SWIFT_EXTENSION(UnifiedVideoEditorSDK)) <UICollectionViewDataSource, UICollectionViewDelegate>
- (NSInteger)collectionView:(UICollectionView * _Nonnull)collectionView numberOfItemsInSection:(NSInteger)section SWIFT_WARN_UNUSED_RESULT;
- (UICollectionViewCell * _Nonnull)collectionView:(UICollectionView * _Nonnull)collectionView cellForItemAtIndexPath:(NSIndexPath * _Nonnull)indexPath SWIFT_WARN_UNUSED_RESULT;
- (void)collectionView:(UICollectionView * _Nonnull)collectionView willDisplayCell:(UICollectionViewCell * _Nonnull)cell forItemAtIndexPath:(NSIndexPath * _Nonnull)indexPath;
@end


SWIFT_CLASS("_TtC21UnifiedVideoEditorSDK10ZipArchive")
@interface ZipArchive : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

#endif
#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#if defined(__cplusplus)
#endif
#pragma clang diagnostic pop
#endif

#elif defined(__x86_64__) && __x86_64__
// Generated by Apple Swift version 5.9.2 (swiftlang-5.9.2.2.56 clang-1500.1.0.2.5)
#ifndef UNIFIEDVIDEOEDITORSDK_SWIFT_H
#define UNIFIEDVIDEOEDITORSDK_SWIFT_H
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#if defined(__OBJC__)
#include <Foundation/Foundation.h>
#endif
#if defined(__cplusplus)
#include <cstdint>
#include <cstddef>
#include <cstdbool>
#include <cstring>
#include <stdlib.h>
#include <new>
#include <type_traits>
#else
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>
#include <string.h>
#endif
#if defined(__cplusplus)
#if defined(__arm64e__) && __has_include(<ptrauth.h>)
# include <ptrauth.h>
#else
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wreserved-macro-identifier"
# ifndef __ptrauth_swift_value_witness_function_pointer
#  define __ptrauth_swift_value_witness_function_pointer(x)
# endif
# ifndef __ptrauth_swift_class_method_pointer
#  define __ptrauth_swift_class_method_pointer(x)
# endif
#pragma clang diagnostic pop
#endif
#endif

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...) 
# endif
#endif
#if !defined(SWIFT_RUNTIME_NAME)
# if __has_attribute(objc_runtime_name)
#  define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
# else
#  define SWIFT_RUNTIME_NAME(X) 
# endif
#endif
#if !defined(SWIFT_COMPILE_NAME)
# if __has_attribute(swift_name)
#  define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
# else
#  define SWIFT_COMPILE_NAME(X) 
# endif
#endif
#if !defined(SWIFT_METHOD_FAMILY)
# if __has_attribute(objc_method_family)
#  define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
# else
#  define SWIFT_METHOD_FAMILY(X) 
# endif
#endif
#if !defined(SWIFT_NOESCAPE)
# if __has_attribute(noescape)
#  define SWIFT_NOESCAPE __attribute__((noescape))
# else
#  define SWIFT_NOESCAPE 
# endif
#endif
#if !defined(SWIFT_RELEASES_ARGUMENT)
# if __has_attribute(ns_consumed)
#  define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
# else
#  define SWIFT_RELEASES_ARGUMENT 
# endif
#endif
#if !defined(SWIFT_WARN_UNUSED_RESULT)
# if __has_attribute(warn_unused_result)
#  define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
# else
#  define SWIFT_WARN_UNUSED_RESULT 
# endif
#endif
#if !defined(SWIFT_NORETURN)
# if __has_attribute(noreturn)
#  define SWIFT_NORETURN __attribute__((noreturn))
# else
#  define SWIFT_NORETURN 
# endif
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA 
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA 
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA 
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif
#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif
#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER 
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility) 
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if !defined(SWIFT_DEPRECATED_OBJC)
# if __has_feature(attribute_diagnose_if_objc)
#  define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
# else
#  define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
# endif
#endif
#if defined(__OBJC__)
#if !defined(IBSegueAction)
# define IBSegueAction 
#endif
#endif
#if !defined(SWIFT_EXTERN)
# if defined(__cplusplus)
#  define SWIFT_EXTERN extern "C"
# else
#  define SWIFT_EXTERN extern
# endif
#endif
#if !defined(SWIFT_CALL)
# define SWIFT_CALL __attribute__((swiftcall))
#endif
#if !defined(SWIFT_INDIRECT_RESULT)
# define SWIFT_INDIRECT_RESULT __attribute__((swift_indirect_result))
#endif
#if !defined(SWIFT_CONTEXT)
# define SWIFT_CONTEXT __attribute__((swift_context))
#endif
#if !defined(SWIFT_ERROR_RESULT)
# define SWIFT_ERROR_RESULT __attribute__((swift_error_result))
#endif
#if defined(__cplusplus)
# define SWIFT_NOEXCEPT noexcept
#else
# define SWIFT_NOEXCEPT 
#endif
#if !defined(SWIFT_C_INLINE_THUNK)
# if __has_attribute(always_inline)
# if __has_attribute(nodebug)
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline)) __attribute__((nodebug))
# else
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline))
# endif
# else
#  define SWIFT_C_INLINE_THUNK inline
# endif
#endif
#if defined(_WIN32)
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL __declspec(dllimport)
#endif
#else
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL 
#endif
#endif
#if defined(__OBJC__)
#if __has_feature(objc_modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import AVFAudio;
@import CoreFoundation;
@import CoreMedia;
@import CoreVideo;
@import Foundation;
@import ObjectiveC;
@import UIKit;
#endif

#endif
#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="UnifiedVideoEditorSDK",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

#if defined(__OBJC__)
@class NSString;
@class NSURL;

SWIFT_PROTOCOL("_TtP21UnifiedVideoEditorSDK8AREffect_")
@protocol AREffect
@property (nonatomic, readonly, copy) NSString * _Nonnull title;
@property (nonatomic, readonly, copy) NSURL * _Nonnull previewImage;
@property (nonatomic, readonly, copy) NSURL * _Nonnull downloadLink;
@property (nonatomic, readonly) BOOL isDownloaded;
/// Do not store localURL. It may be different after relaunching the app.
@property (nonatomic, copy) NSURL * _Nullable localURL;
@property (nonatomic, readonly, copy) NSString * _Nullable type;
@end




@class NSCoder;

SWIFT_CLASS("_TtC21UnifiedVideoEditorSDK21ActivityIndicatorView")
@interface ActivityIndicatorView : UIView
@property (nonatomic) CGRect bounds;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC21UnifiedVideoEditorSDK22AlbumItemConfiguration")
@interface AlbumItemConfiguration : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


/// The Albums configuration
SWIFT_CLASS("_TtC21UnifiedVideoEditorSDK19AlbumsConfiguration")
@interface AlbumsConfiguration : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


@class NSBundle;

SWIFT_CLASS("_TtC21UnifiedVideoEditorSDK19AlertViewController")
@interface AlertViewController : UIViewController
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified contextView;
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified backgroundView;
@property (nonatomic, readonly) UIStatusBarStyle preferredStatusBarStyle;
- (void)viewWillAppear:(BOOL)animated;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end






SWIFT_CLASS("_TtC21UnifiedVideoEditorSDK16AppStateObserver")
@interface AppStateObserver : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class NSNotification;

@interface AppStateObserver (SWIFT_EXTENSION(UnifiedVideoEditorSDK))
- (void)handleApplicationWillResignActiveNotification:(NSNotification * _Nonnull)notification;
- (void)handleApplicationDidBecomeActiveNotification:(NSNotification * _Nonnull)notification;
- (void)handleWillEnterForegroundNotification:(NSNotification * _Nonnull)notification;
- (void)handleWillTerminateNotification:(NSNotification * _Nonnull)notification;
- (void)handleDidEnterBackgroundNotification:(NSNotification * _Nonnull)notification;
@end


SWIFT_PROTOCOL("_TtP21UnifiedVideoEditorSDK24AppStateObserverDelegate_")
@protocol AppStateObserverDelegate
- (void)applicationWillResignActive:(AppStateObserver * _Nonnull)appStateObserver;
- (void)applicationDidBecomeActive:(AppStateObserver * _Nonnull)appStateObserver;
@optional
- (void)applicationWillEnterForeground:(AppStateObserver * _Nonnull)appStateObserver;
- (void)applicationWillTerminateNotification:(AppStateObserver * _Nonnull)appStateObserver;
- (void)applicationDidEnterBackgroundNotification:(AppStateObserver * _Nonnull)appStateObserver;
@end

@class UIScrollView;

SWIFT_CLASS("_TtC21UnifiedVideoEditorSDK22AudioPartSelectionView")
@interface AudioPartSelectionView : UIView <UIScrollViewDelegate>
- (nonnull instancetype)initWithFrame:(CGRect)frame SWIFT_UNAVAILABLE;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder SWIFT_UNAVAILABLE;
- (void)layoutSubviews;
- (void)scrollViewDidScroll:(UIScrollView * _Nonnull)scrollView;
- (void)scrollViewDidEndDecelerating:(UIScrollView * _Nonnull)scrollView;
- (void)scrollViewDidEndDragging:(UIScrollView * _Nonnull)scrollView willDecelerate:(BOOL)decelerate;
- (void)scrollViewWillBeginDragging:(UIScrollView * _Nonnull)scrollView;
- (void)scrollViewWillBeginDecelerating:(UIScrollView * _Nonnull)scrollView;
@end


/// Allows you to implement audio service functionality
SWIFT_CLASS("_TtC21UnifiedVideoEditorSDK12AudioService")
@interface AudioService : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class AVAudioPlayer;

@interface AudioService (SWIFT_EXTENSION(UnifiedVideoEditorSDK)) <AVAudioPlayerDelegate>
- (void)audioPlayerDidFinishPlaying:(AVAudioPlayer * _Nonnull)player successfully:(BOOL)flag;
@end


/// AnalyticsManager is used to interact with banuba analytics servers
SWIFT_CLASS_NAMED("BNBAnalyticsManager")
@interface BNBAnalyticsManager : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end



/// The background configuration.
SWIFT_CLASS("_TtC21UnifiedVideoEditorSDK23BackgroundConfiguration")
@interface BackgroundConfiguration : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


@class NSError;
@class UIImage;
@class UIApplication;

/// Use this class to access Banuba effects from the cloud.
SWIFT_CLASS("_TtC21UnifiedVideoEditorSDK13BanubaARCloud")
@interface BanubaARCloud : NSObject
/// Storing path to the folder witch storing downloaded effects.
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSURL * _Nonnull effectsFolderURL;)
+ (NSURL * _Nonnull)effectsFolderURL SWIFT_WARN_UNUSED_RESULT;
/// Initialize AR cloud client with UUID string.
/// \param arCloudUrl the url that is used to provide effects.
///
/// \param embeddedEffectURLs the list of url to folders which store embedded effects, effects from these folders will be displayed as downloaded.
///
- (nonnull instancetype)initWithArCloudUrl:(NSString * _Nonnull)arCloudUrl embeddedEffectURLs:(NSArray<NSURL *> * _Nullable)embeddedEffectURLs OBJC_DESIGNATED_INITIALIZER;
/// Retrieve ar effects from cloud.
/// Also returns embedded effects which described in embeddedEffectURLs param in init method.
- (void)getAREffectsWithCompletion:(void (^ _Nonnull)(NSArray<id <AREffect>> * _Nullable, NSError * _Nullable))completion;
/// Retrieve the ar effect preview image
- (void)getArEffectPreview:(id <AREffect> _Nonnull)effect completion:(void (^ _Nonnull)(UIImage * _Nullable, NSError * _Nullable))completion;
/// Download the ar effect to local storage.
- (NSUInteger)downloadArEffect:(id <AREffect> _Nonnull)effect downloadProgress:(void (^ _Nullable)(double))downloadProgress completion:(void (^ _Nonnull)(NSURL * _Nullable, NSError * _Nullable))completion;
/// Cancel downloading effect with specific request id.
- (void)cancelDownloadingEffectWithRequestId:(NSUInteger)requestId;
/// This method needs to be called in the UIApplicationDelegate func application(_ application:, handleEventsForBackgroundURLSession identifier:, completionHandler: @escaping () -> Void).
+ (void)application:(UIApplication * _Nonnull)application handleEventsForBackgroundURLSession:(NSString * _Nonnull)identifier completionHandler:(void (^ _Nonnull)(void))completionHandler;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


/// Class supports asynchronous execution block of code
SWIFT_CLASS("_TtC21UnifiedVideoEditorSDK20BanubaAsyncOperation")
@interface BanubaAsyncOperation : NSOperation
@property (nonatomic, readonly, getter=isReady) BOOL ready;
@property (nonatomic, readonly, getter=isExecuting) BOOL executing;
@property (nonatomic, readonly, getter=isFinished) BOOL finished;
@property (nonatomic, readonly, getter=isAsynchronous) BOOL asynchronous;
+ (NSSet<NSString *> * _Nonnull)keyPathsForValuesAffectingValueForKey:(NSString * _Nonnull)key SWIFT_WARN_UNUSED_RESULT;
- (void)start;
/// Subclasses must implement this to perform their work and they must not call <code>super</code>. The default implementation of this function throws an exception.
- (void)main;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC21UnifiedVideoEditorSDK32BaseTrackSelectionViewController")
@interface BaseTrackSelectionViewController : UINavigationController
- (nonnull instancetype)initWithNavigationBarClass:(Class _Nullable)navigationBarClass toolbarClass:(Class _Nullable)toolbarClass OBJC_DESIGNATED_INITIALIZER SWIFT_AVAILABILITY(ios,introduced=5.0);
- (nonnull instancetype)initWithRootViewController:(UIViewController * _Nonnull)rootViewController OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end




SWIFT_CLASS("_TtC21UnifiedVideoEditorSDK14CameraLutStage")
@interface CameraLutStage : NSObject
@property (nonatomic, copy) NSString * _Nonnull name;
@property (nonatomic) BOOL isActive;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_PROTOCOL("_TtP21UnifiedVideoEditorSDK12RenderEffect_")
@protocol RenderEffect
@property (nonatomic, readonly, copy) NSString * _Nonnull name;
@property (nonatomic, readonly) BOOL isLoaded;
@property (nonatomic) BOOL isActive;
- (void)load;
- (void)unload;
- (void)applyWithPixelBuffer:(CVPixelBufferRef _Nonnull)pixelBuffer;
@end


@interface CameraLutStage (SWIFT_EXTENSION(UnifiedVideoEditorSDK)) <RenderEffect>
@property (nonatomic, readonly) BOOL isLoaded;
- (void)load;
- (void)unload;
- (void)applyWithPixelBuffer:(CVPixelBufferRef _Nonnull)pixelBuffer;
@end

@class CALayer;

/// Simple circular progress view
SWIFT_CLASS("_TtC21UnifiedVideoEditorSDK20CircularProgressView")
@interface CircularProgressView : UIView
- (void)layoutSublayersOfLayer:(CALayer * _Nonnull)layer;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


/// The Composition Timeline configuration
SWIFT_CLASS("_TtC21UnifiedVideoEditorSDK32CompositionTimelineConfiguration")
@interface CompositionTimelineConfiguration : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end



/// Setups drafts feature
typedef SWIFT_ENUM(NSInteger, DraftsFeatureConfig, open) {
/// Drafts enabled. Alert asking for saving video to drafts will be presented after editing a video. Drafts button on the start screen  is displayed.
  DraftsFeatureConfigEnabled = 0,
/// Drafts enabled. No alert will be presented after editing a video. Drafts button on the start screen is displayed.
  DraftsFeatureConfigEnabledSaveToDraftsByDefault = 1,
/// Drafts disabled completely. Drafts button on the start screen is hidden.
  DraftsFeatureConfigDisabled = 2,
/// Drafts enabled. Cover screen will not be presented after editing a video.
  DraftsFeatureConfigEnabledAskIfSaveNotExport = 3,
};


/// Holder contains set of speed and visual effexts
SWIFT_CLASS("_TtC21UnifiedVideoEditorSDK25EditorEffectsConfigHolder")
@interface EditorEffectsConfigHolder : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC21UnifiedVideoEditorSDK11EffectModel")
@interface EffectModel : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end




@class UIButton;

SWIFT_CLASS("_TtC21UnifiedVideoEditorSDK22FullscreenActivityView")
@interface FullscreenActivityView : UIView
@property (nonatomic, weak) IBOutlet UIButton * _Nullable additionalButton;
- (void)awakeFromNib;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


/// The Gallery configuration
SWIFT_CLASS("_TtC21UnifiedVideoEditorSDK20GalleryConfiguration")
@interface GalleryConfiguration : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end



SWIFT_CLASS("_TtCC21UnifiedVideoEditorSDK35SmallActivityIndicatorConfiguration12GradientType")
@interface GradientType : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class GradientColorConfiguration;
@protocol ImageConfigurationProtocol;

@interface GradientType (SWIFT_EXTENSION(UnifiedVideoEditorSDK))
+ (GradientType * _Nonnull)color:(GradientColorConfiguration * _Nonnull)color SWIFT_WARN_UNUSED_RESULT;
+ (GradientType * _Nonnull)image:(id <ImageConfigurationProtocol> _Nonnull)image SWIFT_WARN_UNUSED_RESULT;
@end

@class UIColor;

/// The image configuration
SWIFT_PROTOCOL("_TtP21UnifiedVideoEditorSDK26ImageConfigurationProtocol_")
@protocol ImageConfigurationProtocol
@property (nonatomic, readonly, strong) UIImage * _Nullable image;
@property (nonatomic, readonly, strong) UIColor * _Nullable tintColor;
@end


/// The image configuration
SWIFT_CLASS("_TtC21UnifiedVideoEditorSDK18ImageConfiguration")
@interface ImageConfiguration : NSObject <ImageConfigurationProtocol>
/// Image tint color
/// Default is nil.
@property (nonatomic, strong) UIColor * _Nullable tintColor;
/// The image stored or instance by name
@property (nonatomic, readonly, strong) UIImage * _Nullable image;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end



SWIFT_CLASS("_TtC21UnifiedVideoEditorSDK19KeyboardLayoutGuide")
@interface KeyboardLayoutGuide : UILayoutGuide
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER SWIFT_UNAVAILABLE;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class TimeBomb;

SWIFT_CLASS("_TtC21UnifiedVideoEditorSDK7License")
@interface License : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull token;
@property (nonatomic, readonly, copy) NSString * _Nonnull clientId;
@property (nonatomic, readonly) int32_t maxFaces;
/// Video Editor Analytics
@property (nonatomic, readonly) BOOL collectAnalytics;
/// FAR Analytics
@property (nonatomic, readonly) BOOL supportsAnalytics;
@property (nonatomic, readonly) BOOL videoEditorSupportsFaceAR;
@property (nonatomic, readonly) BOOL hasFaceARFeatures;
@property (nonatomic, readonly, copy) NSArray<NSNumber *> * _Nonnull postProcessingEffects;
@property (nonatomic, readonly, copy) NSString * _Nullable arCloudURL;
@property (nonatomic, readonly, strong) TimeBomb * _Nullable timeBomb;
@property (nonatomic, readonly) BOOL supportsFHD;
@property (nonatomic, readonly) BOOL isExportAPIEnabled;
@property (nonatomic, readonly) BOOL isPlaybackAPIEnabled;
@property (nonatomic, readonly) BOOL isVESDKEnabled;
@property (nonatomic, readonly) BOOL isPhotoEditorSDKEnabled;
- (BOOL)isEqual:(id _Nullable)object SWIFT_WARN_UNUSED_RESULT;
+ (License * _Nullable)getLicenseFromToken:(NSString * _Nonnull)token SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end






SWIFT_CLASS("_TtC21UnifiedVideoEditorSDK7NibView")
@interface NibView : UIView
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


/// UIImageView playable preview.
SWIFT_CLASS("_TtC21UnifiedVideoEditorSDK15PlayablePreview")
@interface PlayablePreview : UIImageView
/// Layer class
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) Class _Nonnull layerClass;)
+ (Class _Nonnull)layerClass SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)initWithImage:(UIImage * _Nullable)image OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithImage:(UIImage * _Nullable)image highlightedImage:(UIImage * _Nullable)highlightedImage OBJC_DESIGNATED_INITIALIZER SWIFT_AVAILABILITY(ios,introduced=3.0);
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC21UnifiedVideoEditorSDK26PopoverAlertViewController")
@interface PopoverAlertViewController : UIViewController
- (void)viewDidLoad;
- (void)viewWillAppear:(BOOL)animated;
- (void)viewWillLayoutSubviews;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end

@class UIGestureRecognizer;
@class UITouch;

@interface PopoverAlertViewController (SWIFT_EXTENSION(UnifiedVideoEditorSDK)) <UIGestureRecognizerDelegate>
- (BOOL)gestureRecognizer:(UIGestureRecognizer * _Nonnull)gestureRecognizer shouldReceiveTouch:(UITouch * _Nonnull)touch SWIFT_WARN_UNUSED_RESULT;
@end




SWIFT_CLASS("_TtC21UnifiedVideoEditorSDK22ProgressViewController")
@interface ProgressViewController : UIViewController
- (void)viewDidLoad;
- (void)viewDidDisappear:(BOOL)animated;
- (void)viewDidLayoutSubviews;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end







SWIFT_CLASS("_TtC21UnifiedVideoEditorSDK9SDKLogger")
@interface SDKLogger : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class UIPresentationController;
@protocol UIViewControllerAnimatedTransitioning;
@protocol UIViewControllerInteractiveTransitioning;

SWIFT_CLASS("_TtC21UnifiedVideoEditorSDK26SlideInPresentationManager")
@interface SlideInPresentationManager : NSObject <UIViewControllerTransitioningDelegate>
- (nonnull instancetype)init;
- (UIPresentationController * _Nullable)presentationControllerForPresentedViewController:(UIViewController * _Nonnull)presented presentingViewController:(UIViewController * _Nullable)presenting sourceViewController:(UIViewController * _Nonnull)source SWIFT_WARN_UNUSED_RESULT;
- (id <UIViewControllerAnimatedTransitioning> _Nullable)animationControllerForPresentedController:(UIViewController * _Nonnull)presented presentingController:(UIViewController * _Nonnull)presenting sourceController:(UIViewController * _Nonnull)source SWIFT_WARN_UNUSED_RESULT;
- (id <UIViewControllerAnimatedTransitioning> _Nullable)animationControllerForDismissedController:(UIViewController * _Nonnull)dismissed SWIFT_WARN_UNUSED_RESULT;
- (id <UIViewControllerInteractiveTransitioning> _Nullable)interactionControllerForPresentation:(id <UIViewControllerAnimatedTransitioning> _Nonnull)animator SWIFT_WARN_UNUSED_RESULT;
- (id <UIViewControllerInteractiveTransitioning> _Nullable)interactionControllerForDismissal:(id <UIViewControllerAnimatedTransitioning> _Nonnull)animator SWIFT_WARN_UNUSED_RESULT;
@end


/// The activity indicator configuration.
SWIFT_CLASS("_TtC21UnifiedVideoEditorSDK35SmallActivityIndicatorConfiguration")
@interface SmallActivityIndicatorConfiguration : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

/// The gradient type.
typedef SWIFT_ENUM(NSInteger, GradientTypeAdapter, open) {
  GradientTypeAdapterColor = 0,
  GradientTypeAdapterImage = 1,
};



/// The gradient configuration.
SWIFT_CLASS("_TtCC21UnifiedVideoEditorSDK35SmallActivityIndicatorConfiguration26GradientColorConfiguration")
@interface GradientColorConfiguration : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end



/// The button configuration with text styling and text.
SWIFT_CLASS("_TtC21UnifiedVideoEditorSDK23TextButtonConfiguration")
@interface TextButtonConfiguration : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


/// The text configuration
SWIFT_CLASS("_TtC21UnifiedVideoEditorSDK17TextConfiguration")
@interface TextConfiguration : NSObject
- (id _Nonnull)copy SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC21UnifiedVideoEditorSDK8TimeBomb")
@interface TimeBomb : NSObject
@property (nonatomic, readonly) NSInteger yearBegin;
@property (nonatomic, readonly) NSInteger monBegin;
@property (nonatomic, readonly) NSInteger dayBegin;
@property (nonatomic, readonly) NSInteger yearEnd;
@property (nonatomic, readonly) NSInteger monEnd;
@property (nonatomic, readonly) NSInteger dayEnd;
@property (nonatomic, readonly) BOOL isExpired;
@end

@protocol TimeLineDataSourceDelegate;

SWIFT_PROTOCOL("_TtP21UnifiedVideoEditorSDK18TimeLineDataSource_")
@protocol TimeLineDataSource
/// TimeLineDataSource delegate object
@property (nonatomic, strong) id <TimeLineDataSourceDelegate> _Nullable delegate;
/// timeline preview
@property (nonatomic, strong) UIImage * _Nullable preview;
/// Asset duration
@property (nonatomic, readonly) CMTime duration;
/// Loaded thumbnails
@property (nonatomic, readonly, copy) NSArray<UIImage *> * _Nonnull thumbnails;
/// Is fetching thumbnails finished
@property (nonatomic, readonly) BOOL isAllThumbnailsFetched;
/// Thumbnails count to fetch
@property (nonatomic, readonly) NSInteger thumbnailsCount;
/// Thumbnails height
@property (nonatomic, readonly) CGFloat thumbnailHeight;
/// Load signle thumbnail for specific second
- (void)loadPreviewWithCompletion:(void (^ _Nonnull)(UIImage * _Nullable))completion at:(double)second;
/// Returns thumbnail at index
- (UIImage * _Nullable)getImageAt:(NSInteger)index SWIFT_WARN_UNUSED_RESULT;
/// Load thumbnails with completion
- (void)loadTimelineThumbsWithCompletion:(void (^ _Nullable)(void))completion;
@end


/// TimeLineDataSourceDelegate notify delegate objects about fetching thumbs actions
SWIFT_PROTOCOL("_TtP21UnifiedVideoEditorSDK26TimeLineDataSourceDelegate_")
@protocol TimeLineDataSourceDelegate
@optional
/// timelineDataSource did preload preivew
- (void)timelineDataSource:(id <TimeLineDataSource> _Nonnull)timelineDataSource didPreloadPreview:(UIImage * _Nonnull)preview;
@required
/// timelineDataSource did load thumb image at index
- (void)timelineDataSource:(id <TimeLineDataSource> _Nonnull)timelineDataSource didLoadImage:(UIImage * _Nonnull)image at:(NSInteger)index;
/// timelineDataSource did finish fetching all thumbs
- (void)timelineDataSourceDidFinishThumbnailFetch:(id <TimeLineDataSource> _Nonnull)timelineDataSource;
@end


/// The Time line configuration
SWIFT_CLASS("_TtC21UnifiedVideoEditorSDK25TrimTimeLineConfiguration")
@interface TrimTimeLineConfiguration : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end












@class NSData;

@interface UIImage (SWIFT_EXTENSION(UnifiedVideoEditorSDK))
/// This method doesn’t use copying data, since it can heavily affect performance and memory usage
/// (for high quality photos like 3024x4032 each copy of data has size ~30 Mb, and on slower devices making copy can take up to 0.2 sec).
/// Common idea - we have NSData object which contains raw data, used for UIImage creation. Since we don’t copy underlying data, we need to take control on
/// lifetime of NSData object, otherwise internal content of UIImage will be destroyed.
/// So, we manually transform NSData object into unmanaged pointer and increase its retain count by passRetained call, and in special callback of CGDataProvider,
/// which will be called when UIImage is no longer needed, we release that unmanaged pointer by takeRetainedValue call, to prevent memory leaks.
- (nullable instancetype)initWithBgraDataNoCopy:(NSData * _Nonnull)bgraDataNoCopy width:(NSInteger)width height:(NSInteger)height;
- (CVPixelBufferRef _Nullable)makeBgraPixelBuffer SWIFT_WARN_UNUSED_RESULT;
@end



















SWIFT_CLASS("_TtC21UnifiedVideoEditorSDK28VideoEditorActivityIndicator")
@interface VideoEditorActivityIndicator : UIView
@property (nonatomic) CGRect bounds;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


/// The video editor launch configuration
SWIFT_CLASS("_TtC21UnifiedVideoEditorSDK23VideoEditorLaunchConfig")
@interface VideoEditorLaunchConfig : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC21UnifiedVideoEditorSDK30VideoImageEffectDrawersFactory")
@interface VideoImageEffectDrawersFactory : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


/// Image composition for slideshow creation
SWIFT_CLASS("_TtC21UnifiedVideoEditorSDK22VideoImagesComposition")
@interface VideoImagesComposition : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC21UnifiedVideoEditorSDK13VideoSequence")
@interface VideoSequence : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end





@interface VideoSequence (SWIFT_EXTENSION(UnifiedVideoEditorSDK))
- (BOOL)isEqual:(id _Nullable)object SWIFT_WARN_UNUSED_RESULT;
@end









/// VideoTimeLineCollectionViewHandler displays timeLineDataSource in collectionView
SWIFT_CLASS("_TtC21UnifiedVideoEditorSDK34VideoTimeLineCollectionViewHandler")
@interface VideoTimeLineCollectionViewHandler : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end



@interface VideoTimeLineCollectionViewHandler (SWIFT_EXTENSION(UnifiedVideoEditorSDK)) <TimeLineDataSourceDelegate>
- (void)timelineDataSource:(id <TimeLineDataSource> _Nonnull)timelineDataSource didPreloadPreview:(UIImage * _Nonnull)preview;
- (void)timelineDataSource:(id <TimeLineDataSource> _Nonnull)timelineDataSource didLoadImage:(UIImage * _Nonnull)image at:(NSInteger)index;
- (void)timelineDataSourceDidFinishThumbnailFetch:(id <TimeLineDataSource> _Nonnull)timelineDataSource;
@end

@class UICollectionView;
@class UICollectionViewLayout;
@class NSIndexPath;

@interface VideoTimeLineCollectionViewHandler (SWIFT_EXTENSION(UnifiedVideoEditorSDK)) <UICollectionViewDelegateFlowLayout>
- (CGSize)collectionView:(UICollectionView * _Nonnull)collectionView layout:(UICollectionViewLayout * _Nonnull)collectionViewLayout sizeForItemAtIndexPath:(NSIndexPath * _Nonnull)indexPath SWIFT_WARN_UNUSED_RESULT;
- (CGFloat)collectionView:(UICollectionView * _Nonnull)collectionView layout:(UICollectionViewLayout * _Nonnull)collectionViewLayout minimumInteritemSpacingForSectionAtIndex:(NSInteger)section SWIFT_WARN_UNUSED_RESULT;
- (CGFloat)collectionView:(UICollectionView * _Nonnull)collectionView layout:(UICollectionViewLayout * _Nonnull)collectionViewLayout minimumLineSpacingForSectionAtIndex:(NSInteger)section SWIFT_WARN_UNUSED_RESULT;
@end

@class UICollectionViewCell;

@interface VideoTimeLineCollectionViewHandler (SWIFT_EXTENSION(UnifiedVideoEditorSDK)) <UICollectionViewDataSource, UICollectionViewDelegate>
- (NSInteger)collectionView:(UICollectionView * _Nonnull)collectionView numberOfItemsInSection:(NSInteger)section SWIFT_WARN_UNUSED_RESULT;
- (UICollectionViewCell * _Nonnull)collectionView:(UICollectionView * _Nonnull)collectionView cellForItemAtIndexPath:(NSIndexPath * _Nonnull)indexPath SWIFT_WARN_UNUSED_RESULT;
- (void)collectionView:(UICollectionView * _Nonnull)collectionView willDisplayCell:(UICollectionViewCell * _Nonnull)cell forItemAtIndexPath:(NSIndexPath * _Nonnull)indexPath;
@end


SWIFT_CLASS("_TtC21UnifiedVideoEditorSDK10ZipArchive")
@interface ZipArchive : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

#endif
#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#if defined(__cplusplus)
#endif
#pragma clang diagnostic pop
#endif

#else
#error unsupported Swift architecture
#endif
